package com.mhmh2.englishbite.ui.theme

import androidx.compose.ui.graphics.Color

// "Midnight Executive Broadcast" - the Material3 tonal dark palette generated by Google's
// Stitch AI design tool from a description of this app. Kept as literal Stitch output for now;
// see project notes for the tradeoff against the previous fixed, non-dynamic BiteBlue palette.
val BiteBlue = Color(0xFFAFC6FF)
val OnBiteBlue = Color(0xFF002D6D)
val BiteBluePressed = Color(0xFF538DFF)
val OnBiteBluePressed = Color(0xFF002760)

val Secondary = Color(0xFF6AD3FA)
val OnSecondary = Color(0xFF003544)
val SecondaryContainer = Color(0xFF219CC1)
val OnSecondaryContainer = Color(0xFF002E3C)

val TertiaryError = Color(0xFFFFB4AB)
val OnTertiaryError = Color(0xFF690005)
val TertiaryErrorContainer = Color(0xFFFF5449)
val OnTertiaryErrorContainer = Color(0xFF5C0004)

val ErrorRed = Color(0xFFFFB4AB)
val OnErrorRed = Color(0xFF690005)
val ErrorContainer = Color(0xFF93000A)
val OnErrorContainer = Color(0xFFFFDAD6)

// Dark, streaming-app-style neutrals, now the Stitch-generated surface tonal ramp rather than
// the previous hand-picked Ink900/800/700/600 steps.
val Ink900 = Color(0xFF0E0E12) // surface-container-lowest
val SurfaceContainerLow = Color(0xFF1B1B1F)
val Ink800 = Color(0xFF131317) // surface / background / surface-dim
val Ink700 = Color(0xFF1F1F23) // surface-container
val SurfaceContainerHigh = Color(0xFF2A292E)
val Ink600 = Color(0xFF353439) // surface-container-highest / surface-variant
val SurfaceBright = Color(0xFF39393D)

val TextPrimary = Color(0xFFE4E1E7) // on-surface / on-background
val TextSecondary = Color(0xFFC2C6D7) // on-surface-variant
val Outline = Color(0xFF8C90A0)
val OutlineVariant = Color(0xFF424754)
val InverseSurface = Color(0xFFE4E1E7)
val InverseOnSurface = Color(0xFF303034)
val InversePrimary = Color(0xFF0059C8)

// Karaoke word-highlight color - kept distinct from the brand accent so spoken-word
// highlighting still reads as its own thing against buttons/badges. Now Stitch's secondary
// cyan rather than the previous hand-picked KaraokeHighlightBlue.
val KaraokeHighlightBlue = Color(0xFF6AD3FA)
